// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBGptlacb2vj_pXWTmGVq804UtkBWcds',
    appId: '1:182103350827:web:67a52a5ff8c73548d2146e',
    messagingSenderId: '182103350827',
    projectId: 'one-of-100-38789',
    authDomain: 'one-of-100-38789.firebaseapp.com',
    storageBucket: 'one-of-100-38789.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB48DW6L1kbWTQBGCczym49H9mLySNkd9Q',
    appId: '1:182103350827:android:177c1a24eae46a44d2146e',
    messagingSenderId: '182103350827',
    projectId: 'one-of-100-38789',
    storageBucket: 'one-of-100-38789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqazitPhcqlBSLIU1i7m6zqONsV1gfYU',
    appId: '1:182103350827:ios:fa883cea4c47fa13d2146e',
    messagingSenderId: '182103350827',
    projectId: 'one-of-100-38789',
    storageBucket: 'one-of-100-38789.appspot.com',
    iosBundleId: 'com.example.oneOff100',
  );
}
